# Generated by Django 3.1.5 on 2021-01-24 18:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeCompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='название_компании')),
            ],
        ),
        migrations.CreateModel(
            name='FakeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='FakeIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_ip_address', models.CharField(max_length=15, verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='FakePhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер_телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=50)),
                ('schema_delimiter', models.CharField(choices=[(',', ','), ('%', '%'), ('/', '/'), ('!', '!')], max_length=1, null=True)),
                ('schema_string_character', models.CharField(choices=[('@', '@'), ('"', '"'), ('&', '&')], max_length=1, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания схемы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сэта')),
                ('csv_file', models.FileField(blank=True, upload_to='csvs/')),
                ('is_ready', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='csv_gen.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('column_type', models.CharField(choices=[('integer', 'integer'), ('phone_number', 'phone_number'), ('company_name', 'company_name'), ('address', 'address'), ('date', 'date')], max_length=30)),
                ('column_type_option_from', models.IntegerField(blank=True, null=True)),
                ('column_type_option_to', models.IntegerField(blank=True, null=True)),
                ('column_order', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='csv_gen.schema')),
            ],
        ),
    ]
