# Generated by Django 3.1.5 on 2021-01-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakecompanyname',
            old_name='company_name',
            new_name='fake_company_name',
        ),
        migrations.RenameField(
            model_name='fakedate',
            old_name='date',
            new_name='fake_date',
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema_delimiter',
            field=models.CharField(choices=[('%', '%'), ('/', '/'), (',', ','), ('!', '!')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema_string_character',
            field=models.CharField(choices=[('"', '"'), ('@', '@'), ('&', '&')], max_length=1, null=True),
        ),
    ]
